# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://cusehacks.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
#social:
#  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "CuseHacks | February 15th - 16th | Life Sciences Complex"
  description: "This will be the third event of Syracuse University's first student-run hackathon."

# Event information.
event:
  name:        "CuseHacks"
  description: "This will be the third event of Syracuse University's first student-run hackathon."
  date:        "February 15th - 16th"
  year:        "2020"
  location:    "Life Sciences Complex"
  school:      "Syracuse University"

# trust_badge:
#   year:   "2019"  # season year
#   region: "na"    # "na" or "eu"
#   color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

hero:
  links:
    - text: "Apply"
      href: https://forms.gle/r9aAbo6eF76AbMwZ7
      # my_mlh:
        # client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
        # redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
    - text: "Sponsor"
      href: "/assets/CuseHacks2020_Sponsorship_Package.pdf"

# Images
image:
  header:     "/images/cuse_hacks_header.png"
  sun:        "/images/sun_gradient.png"
  about:      "/images/about.png"
  palm_trees: "/images/palm_trees.png"
  faq:        "/images/faqs.png"
  sponsors:   "/images/sponsors.png"
  mountains:  "/images/mountains.png"
  sign_up:    "/images/sign_up.png"
  slice:      "/images/logos/cusehacks_logo.png"
  

# About Information
about:
  - paragraph_header: ""
    paragraph_content: >
      CuseHacks is the first student-run hackathon at Syracuse University. Over a span of 24-hours, students of all backgrounds are invited
      to explore the possiblities of technology and imagination.
  - paragraph_header: "In 2020, Syracuse University will welcome back it’s student-run hackathon – CuseHacks."
    paragraph_content: >
      College students around the northeast region are invited to spend 24 hours hacking to build cool and innovative applications, websites, and hardware projects.
  - paragraph_header: "You do not need to know how to code to participate."
    paragraph_content: >
      Designers, Artists, Entrepreneurs, Engineers, and anyone interested in creating are encouraged to participate.
      We are dedicated to facilitating a welcoming environment for everyone, particularly beginners.
      Mentors and volunteers will be there to help you by answering questions, leading fun workshops, and guiding you on your hack.
  - paragraph_header: "It will be fun."
    paragraph_content: >
      Throughout the weekend, you can use your imagination to make anything you want with the help of your amazing peers and impressive mentors.
      There will be games, food, and swag! Build something or break something.
      CuseHacks just wants you to have a great experience meeting new people, working with friends, and gaining new skills, learning about the possibilities of technology.

# Frequently asked questions.
faq:
  - question: "What is a hackathon?"
    answer: >
      A hackathon is an invention marathon. Students come together to build cool
      software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
      CuseHacks is not your typical hackathon. We encourage students with any level of experience to sign up.
  - question: "How much does it cost?"
    answer: >
      Nothing. Attending a hackathon is free, and we will provide meals, snacks, and swag throughout the event.
  - question: "Who can participate?"
    answer: >
      All current college students are invited to participate. We will be capping attendance, so please register ASAP!
  - question: "Will there be travel reimbursement?"
    answer: >
      We can not ensure travel reimbursements right now, but it may be a possibility. Please email innovateorange@gmail.com for more information.
  - question: "What if I don't have coding or hackathon experience?"
    answer: >
      Beginners are especially encouraged to come! You do not need previous hackathon/coding experience or a technology
      background. CuseHacks is meant to be a comfortable learning experience for everyone. Also, there will be workshops
      and mentors available throughout the event that can help you get started.
  - question: "How do teams work?"
    answer: >
      Each team can have up to as many members as you want. Typically teams run from 3-4 members. You can come with your friends or you can form a team at the event.
      There will be team forming activities at the beginning of the hackathon for anybody interested. You can also work alone if you want.
  - question: "Where is the event?"
    answer: >
      The event location is at the Life Science Complex Building at Syracuse University.
  - question: "Your question not here?"
    answer: >
      Please email innovateorange@gmail.com for any more questions.
  - question: "What is Major League Hacking?"
    answer: >
      Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
      We work with over 200 Member Events and empower over 70,000 students every year.
  - question: "Is there a code of conduct?"
    answer: >
      Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

# Sponsor Information
sponsor:
  message: "Thank you to the Department of Electrical Engineering and Computer Science, David G. Edelstein, and our other sponsors for collaborating with us."
  logo:
    case:         "/images/logos/case_logo.png"
    dibellas:     "/images/logos/dibellas_logo.png"
    ecs:          "/images/logos/ecs_logo.png"
    eecs:         "/images/logos/eecs_logo.png"
    google_cloud: "/images/logos/google_cloud_logo.png"
    google:       "/images/logos/google_logo.png"
    ibm:          "/images/logos/ibm_logo.png"
    lockheed:     "/images/logos/lockheed_logo.png"
    mlh:          "/images/logos/mlh_logo.png"
    rockstar:     "/images/logos/rockstar_logo.png"
    src:          "/images/logos/src_logo.png"
    twitch:       "/images/logos/twitch_logo.png"
    utc:          "/images/logos/utc_logo.png"
    wegmans:      "/images/logos/wegmans_logo.png"


# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
