# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://cusehacks.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
#social:
#  twitter_handle: "MLHacks"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "CuseHacks | February 15th - 16th"
  description: "Site Under Construction"
image:       "/images/walt_the_crane.png"

# Event information.
event:
  name:        "CuseHacks"
  description: "This site is under construction. We'll be back soon with a brand new site."
  date:        "February 15th - 16th"
  location:    "Syracuse, NY, United States"

  # trust_badge:
  #   year:   "2017"  # season year
  #   region: "eu"    # "na" or "eu"
  #   color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        href: https://forms.gle/r9aAbo6eF76AbMwZ7
        # my_mlh:
          # client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          # redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "/assets/CuseHacks2019_Sponsorship_Package.pdf"

  about:
    description: >
      Site Under Construction

  # Info Sections
  #info:
  #  sections:
  #    - image: "images/image1.png"
  #      title: "LEARN."
  #      description: >
  #        We can write something nice with a graphic (as above) to make the event more appealing.
  #    - image: "images/image2.png"
  #      title: "BUILD."
  #      description: >
  #        We can write something nice with a graphic (as above) to make the event more appealing.
  #    - image: "images/image3.png"
  #      title: "SHARE."
  #      description: >
  #        We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
